# -*- coding: utf-8 -*-
"""First.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ibVzZAzNKh3uex6z4K7IJnG6QNIBaPi0
"""

L1=[2,4,6,8,10]
L2=[1,3,5,7,9]

print (L1+L2)

type(L1)

L1=[0,30,45,60,90,120,180,270,360]

angle=list(range(0,361,30))
print(angle)
i1=angle.index(90)
i2=angle.index(270)
i1_rev=i1-len(angle)
i2_rev=i1-len(angle)
angle2=angle[i2_rev:i1_rev-1:-1]
print(angle2)

L1=[2,4,8,9,10]
L2=L1
del(L2[3])
print(L2)
print(L1)
L4=L1.copy
del(L2[3])
print(L4,L1)

L3=L1[:] #or L3=L1.copy
del(L3[3])
print(L3)

import numpy as np
import tensorflow as tf

#import pytorch

tup1=(1,2,3)
tup2=(4,5,6)
tup3=(7,8,9)
tup1=tup1+(11,)
print(tup1)
tup4=tup1[:1]+tup1[2:]
print(tup4)

def circumference(r):
  cir=2*3.14(r)
  return(cir)

x = lambda a, b, c: a/b/c
print(x(5, 6, 2))

define my_function(fname):
  print(fname +  " hai")
  my_function("sweety")
  my_function("Bubbly")

x = True
print(x)
print(type(x))

print ("Hello World")